export const THEME = {
  name: "Brutalist",
  bg: "#f8f8f8",
  cardBg: "#fff",
  cardBorder: "2px solid #111",
  headerBg: "#f0f0f0",
  headerText: "#111",
  text: "#111",
  textMuted: "#555",
  accent: "#111",
  currentBg: "#111",
  currentText: "#fff",
  currentMuted: "#aaa",
  highBg: "#111",
  highText: "#fff",
  lowBg: "#fff",
  lowText: "#111",
  lowBorder: "#111",
  selectedBg: "#111",
  selectedText: "#fff",
  todayBorder: "#111",
  curveStroke: "#111",
  curveDot: "#111",
  curveDotLow: "#fff",
  barBg: "#e5e5e5",
  barFill: "#111",
  sunMoonBg: "#f5f5f5",
  sunColor: "#d97706",
  fontFamily: '"SF Mono", Consolas, monospace',
  borderRadius: "0",
  shadow: "none"
} as const

export type ThemeConfig = typeof THEME
