import Foundation
import Testing

/// The parity contract for the Swift port: the committed language-neutral
/// fixtures (generated by `pnpm fixtures`, see CONTRIBUTING.md) are what the
/// Swift engine must reproduce to 1e-9 m / 1 s (packages/core/test/fixtures.test.ts).
///
/// This suite currently pins the harness itself — fixture location, JSON
/// shapes, counts, and semantic invariants — so the engine port can grow
/// against it step by step.
struct FixtureHarnessTests {
    static let fixturesURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // TidesCoreTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // TidesCore
        .deletingLastPathComponent() // ios
        .deletingLastPathComponent() // repo root
        .appendingPathComponent("packages/core/fixtures")

    struct Level: Decodable {
        let utc: String
        let level: Double
    }

    struct ExtremeWindow: Decodable {
        struct Extreme: Decodable {
            let utc: String
            let level: Double
            let type: String
        }

        let fromUtc: String
        let toUtc: String
        let extremes: [Extreme]
    }

    struct StationDay: Decodable {
        struct Day: Decodable {
            let year: Int
            let month: Int
            let day: Int
        }

        struct Extreme: Decodable {
            let utc: String
            let height: Double
            let type: String
        }

        let day: Day
        let tz: String
        let extremes: [Extreme]
    }

    func load<T: Decodable>(_ name: String, as _: T.Type) throws -> T {
        let data = try Data(contentsOf: Self.fixturesURL.appendingPathComponent(name))
        return try JSONDecoder().decode(T.self, from: data)
    }

    @Test func levelsFixtureDecodes() throws {
        let levels = try load("levels.json", as: [Level].self)
        #expect(levels.count == 2000)
    }

    @Test func extremesFixtureDecodesAndAlternates() throws {
        let windows = try load("extremes.json", as: [ExtremeWindow].self)
        #expect(!windows.isEmpty)
        for window in windows where window.extremes.count > 1 {
            for i in 1 ..< window.extremes.count {
                #expect(window.extremes[i].type != window.extremes[i - 1].type)
            }
        }
    }

    @Test func stationDaysFixtureDecodes() throws {
        let days = try load("station-days.json", as: [StationDay].self)
        #expect(days.count == 25)
        #expect(days.allSatisfy { $0.tz == "Europe/Jersey" })
    }
}
